### ISSUE TITLE
Some comments and suggestions to the contribution process

### ISSUE THREAD

**Issue by CsatariGergely** [cncf/telecom-user-group#42]
Hi, 
I would have some suggestions to the contribution process:

- I think we do not need labels yet, so I would remove the related statements
- I would not require an issue to create pr. This just slows down the creation of pr. We can reject pr-s any time :)

**Comment by CsatariGergely** [comment]
@tomkivlin

**Comment by tomkivlin** [comment]
@taylor @ASalkever @dankohn - thoughts?  I'm easy either way, the purpose of the requirement to include an Issue was just to avoid too much wasted work, but if people are happy to accept that risk then fine by me.

**Comment by taylor** [comment]
@CsatariGergely, @tomkivlin, I'm fine with people opening PRs w/o issues.  Basically, create a PR when you are ready to propose the change and create an issue when you think there needs to be discussion.

Some thoughts on creating a PR/issue:
- If you are clear on the changes and think there is no need for more discussion then create a PR
- Break up changes into smaller chunks when possible so the PR review and acceptance is likely to occur sooner
- If you think there is unlikely to be consensus on a point then feel free to create an issue to discuss further
- If an existing PR is blocked because a change can't come to consensus open an issue to continue the discussion and see if the other parts of the PR can be accepted.
- If you want to brainstorm / spec out and idea create an issue
- If there is an existing issue when a PR is created then reference the issue

No comment on labels atm.

**Comment by ASalkever** [comment]
I would just bias towards the simplest possible way to get things done.
Since I rarely (well, almost never :) ) use Github to edit documents, I am
not super comfortable commenting on which specific pieces work the best and
defer. The goal to me is to get this done ASAP.

**Comment by taylor** [comment]
@CsatariGergely, would you please make a PR to the [CONTRIBUTING](https://github.com/cncf/telecom-user-group/blob/master/CONTRIBUTING.md) document regarding the updates?  

For labels, I presume you are referring to the [issues section](https://github.com/cncf/telecom-user-group/blob/master/CONTRIBUTING.md#issues).  The idle labels for PR are for who maintenance of older requests and not expected by the PR submitter.

For the [issue requirement for PRs ](https://github.com/cncf/telecom-user-group/blob/master/CONTRIBUTING.md#pull-requests)please update the wording to use language that indicates it's optional or recommended. I'm good either way and in general agree with encouraging contributions via PR by lowering the barrier.
