### ISSUE TITLE
[whitepaper][1.3.1] What is vertical scalability in case of microservices?

### ISSUE THREAD

**Issue by CsatariGergely** [cncf/telecom-user-group#43]
Chapter 1.3.1 talks about the vertical scalability of microservices. This in practice means that we sould change the the available resources of the pods while they are running. I do not think that vertical scalability should be supported.

**Comment by jeffsaelens** [comment]
I agree. Vertically scaling a workload breaks the immutable principles. Following those principles, the workload should either be scaled horizontally or redeployed with the desired end state. A Blue/Green deployment is probably a valid option should a redeployment be needed for a running workload.

**Comment by dankohn** [comment]
The aspiration of vertical scaling is that a gold CNF could provide better performance on bigger nodes (e.g., more CPU or memory) rather than being tied to a single configuration. 

I agree that the expectation is that you would redeploy on a bigger or smaller node and then kill the original, rather than dynamically resizing the node a CNF is currently deployed to.

**Comment by ASalkever** [comment]
@CsatariGergely @jeffsaelens - I filed a PR to remove vertical and horizontal and leave it at scalability per microservice.

**Comment by taylor** [comment]
merged change
